name: Jonas W
favicon: null
layout_spectrum: 0.85039
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#121212'
    - '#ed544c'
    - '#fbc673'
    - '#999999'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0
purpose: []
