name: Jonas W
favicon: null
layout_spectrum: 0.6336724597495049
typography_spectrum: 0.1736949507612735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#121212'
    - '#ed544c'
    - '#fbc673'
    - '#999999'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
