purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 1
  rhythmicContrast: 0.5
  brandColors:
    - '#ffffff'
    - '#121212'
    - '#ed544c'
    - '#fbc673'
    - '#999999'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
name: Jonas W
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4713262
layout_spectrum: 0.9175627
